### ISSUE TITLE
Add proper support for attaching

### ISSUE THREAD

**Issue by frqmod** [mahaloz/decomp2dbg#34]
Currently support for using the `attach` command is shaky with PIE binaries, and requires the strict process of launching a new gdb instances, attaching to the target process id, and then connecting to decomp2dbg. Attempting to attach again after this will cause the attached-to binary to have a new base address, and I assume this prevents decomp2dbg from functioning properly as I lose symbols after that. On my local system, disconnecting and reconnecting doesn't fix this (if done before or after the binary is attached to for the second time).

**Comment by mahaloz** [comment]
Ok, so this is apparently a result of two compounding problems. First:
https://github.com/mahaloz/decomp2dbg/blob/57983617d9a14f1f2ed7b54ee07bd15f14075c45/decomp2dbg/clients/gdb/gdb_client.py#L245

On this line we actually never reinitialize the base address on new connection. We should though so this is a bug for sure. But the second one is not a bug. The second issue is in this function:

https://github.com/mahaloz/decomp2dbg/blob/57983617d9a14f1f2ed7b54ee07bd15f14075c45/decomp2dbg/clients/gdb/utils.py#L74

This is how we get the base address of the binary. Because two things in memory can share the same name, we actually do a full hash comparison of the two things in memory. This is a very costly process, so we probably want this to only happen once.
