### ISSUE TITLE
Drop simpleXPCServer, use fastAPI

### ISSUE THREAD

**Issue by 0xMirasio** [mahaloz/decomp2dbg#74]
Hello, was asking if this can be usefull and worth dev time (can do it) to drop simpleXPCServer (poor performance, very slow) and use fastAPI (which will reduce latence very much). the code transformation isn't difficult the framework are very simillar (Server/client)

**Comment by 0xMirasio** [comment]
I can send you a merge request for poc if you want:

most of server code transform into this :


```
from fastapi import FastAPI
from pydantic import BaseModel

app = FastAPI()

class DecompilationResponse(BaseModel):
    decompilation: str
    curr_line: int
    func_name: str

@app.get("/decompile/", response_model=DecompilationResponse)
def decompile(addr: int):
    return {
        "decompilation": "some_code",
        "curr_line": 5,
        "func_name": "some_func"
    }

class FunctionDataResponse(BaseModel):
    args: dict
    stack_vars: dict

@app.get("/function_data/", response_model=FunctionDataResponse)
def function_data(addr: int):
    return {
        "args": {0x0: {"name": "example_name", "type": "some_type"}},
        "stack_vars": {0x10: {"name": "example_name", "type": "some_type"}}
    }

class FunctionHeadersResponse(BaseModel):
    headers: dict

@app.get("/function_headers/", response_model=FunctionHeadersResponse)
def function_headers():
    return {"headers": {0xdeadbeef: {"name": "func_name", "size": 100}}}

class GlobalVarsResponse(BaseModel):
    globals: dict

@app.get("/global_vars/", response_model=GlobalVarsResponse)
def global_vars():
    return {"globals": {0xdeadbeef: {"name": "var_name"}}}

class StructsResponse(BaseModel):
    structs: dict

@app.get("/structs/", response_model=StructsResponse)
def structs():
    return {
        "structs": {
            "example_struct_name": {
                "size": 100,
                "example_member_name": {"offset": 5, "size": 10}
            }
        }
    }

class BreakpointsResponse(BaseModel):
    breakpoints: dict

@app.get("/breakpoints/", response_model=BreakpointsResponse)
def breakpoints():
    return {
        "breakpoints": {
            0xdeadbeef: True,
            0xdeadbeef + 1: False
        }
    }

@app.get("/ping/")
def ping():
    return {"ping": True}

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="localhost", port=3662)
```

**Comment by mahaloz** [comment]
@0xMirasio I took a look at your proposed framework shift to [fastAPI](https://fastapi.tiangolo.com/). Although I think it looks simple and fast, I think it's not a good match for d2d. The chief concern I have is that fastAPI appears to be only for Python. One of the major platforms we support is Ghidra, which is completely written in Java on the _server side_: 
https://github.com/mahaloz/decomp2dbg/tree/main/decompilers/d2d_ghidra

The code you have listed above is for the server-side, which would obviously not work on Ghidra. Secondly, an important reason I chose XMLRPC, although slow af, was because it was simple to install and integrate. XMLRPC is built into Python. This means we don't need to install it. That becomes very important when you look at the context of these decompiler plugins. Look at IDA, for instance: 
https://github.com/mahaloz/decomp2dbg/blob/main/decompilers/d2d_ida/d2d_ida/server.py

Notice that there are actually **no** install requirements on the server side. That means people don't need to struggle to find their decompilers Python instance since they can just chuck that server file in as-is. 

## Summarization
To summarize, I think fastAPI does not work because:
1. It does not work on Java
2. It requires external libraries to be installed into each decompiler 

## Cavet for fastAPI to be accepted
Although I am opposed right now to fastAPI, **with the right numbers, I can be convinced**. If you do decide to reimplement this in fastAPI, do a simple plugin like IDA or Binja. Record the speed gain differences (time to update context tab in gdb). If the numbers are really big, like a `40%` gain in speed or something, I would be much more open to pushing this change. If the numbers are good, I would need to complete the following PRs, which I will link below. 

### Convert Ghidra to Python Only
We use BinSync code for nearly everything. If this gets merged: https://github.com/binsync/binsync/pull/312, than we will have it shortly after. 

### Update installer for Decompiler Deps
Update the d2d installer so things will be installed inside the decompiler now.

**Comment by 0xMirasio** [comment]
hello thanks for the response. well if i have time i will try to do the integration for ida and test response time and perfs checks. 

for the external lib things, yep it can be installed inside your install scripts. 

i think imo there is no really big problems to install externals python libs as yout project will probably grow bigger and requires more libs for functionnality. i also forget about ghidra. dont know whats binsync and if python is possible gor ghidra / fastapi in java will look for it

**Comment by mahaloz** [comment]
> I think imo there is no really big problems to install externals python libs as yout project will probably grow bigger and requires more libs for functionality.

I designed d2d in such a way that all dependencies were installed on the client side, since I couldn't ever see needing libraries in the decompiler. All we do is gather essentially strings and send them to the client, which then does all the complicated stuff of this project. 

Installing things into the decompiler Python is _complicated_. It requires the user to know what Python instance their decompiler uses. It has to be done manually. In Binja, this Python is obscured behind a Binja specific venv. In IDA on MacOS, this is nearly impossible to find automatically.

**Comment by mahaloz** [comment]
Oh and to update, you need not worry about the linked PR to BinSync. Should the numbers happen to be compelling, I will push the BinSync PR to completion.

**Comment by casept** [comment]
I'm currently working on a decomp2dbg client library for Frida.

With XMLRPC, it's reasonably easy for me to implement this in-process by manually banging out HTTP requests via Frida's Socket API.

Having to integrate a Python library for this would either require me to write an external tool (meaning that it'd no longer be possible to use my library with a standalone Frida gadget), or do the painful work of manually implementing a Javascript version of fastAPI.

**Comment by bjorn3** [comment]
Would using JSON-RPC work? It is similar in structure to XML-RPC and has many implementations including python and javascript ones. And shouldn't be too hard to implement in any language for which a json implementation exists.

**Comment by mahaloz** [comment]
@casept, thanks for the added input. This is why I'm hesitant to do it; however, if it ends up just being _too_ good, it may be worth it in my eyes. But for now, it will stay as XMLRPC. 

@bjorn3 same with the fastAPI move, if some one can show me some numbers concerning a speedup using JSON-RPC, than I will consider switching everything over. For now, XMLRPC remains the king because it's built-in to Python.

**Comment by mahaloz** [comment]
Since this convo has gone stale, I'll close it. Feel free to reopen if more discussion is wanted.
